export const CONFIG = {
  TRAVEL_FEE_PER_KM: Number(process.env.NEXT_PUBLIC_TRAVEL_FEE_PER_KM),
  FREE_TRAVEL_DISTANCE_KM: Number(
    process.env.NEXT_PUBLIC_FREE_TRAVEL_DISTANCE_KM,
  ),
  POINTS_PER_UNIT: Number(process.env.NEXT_PUBLIC_POINTS_PER_UNIT),
  PESO_PER_POINTS: Number(process.env.NEXT_PUBLIC_PESO_PER_POINTS),
  PERCENTAGE_LIMIT: Number(process.env.NEXT_PUBLIC_PERCENTAGE_LIMIT),
  DOWN_PAYMENT_PERCENTAGE: Number(
    process.env.NEXT_PUBLIC_DOWN_PAYMENT_PERCENTAGE,
  ),
  BASE_URL: String(process.env.NEXT_PUBLIC_BASE_URL),
  MINIMUM_REDEEM_POINTS: Number(process.env.NEXT_PUBLIC_MINIMUM_REDEEM_POINTS),
  DOWN_PAYMENT_MULTIPLIER:
    Number(process.env.NEXT_PUBLIC_DOWN_PAYMENT_PERCENTAGE) / 100,
  PERCENTAGE_LIMIT_MULTIPLIER:
    Number(process.env.NEXT_PUBLIC_PERCENTAGE_LIMIT) / 100,
};
